import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import * as echarts from 'echarts';
import {Activity, LayoutDashboard, FlaskConical, GitCompareArrows, Film, FolderOpen, ChevronRight, Download, ArrowLeft, Cpu, RefreshCw, Search, ExternalLink} from 'lucide-react';
import './style.css';

type Data = Record<string, any>;
const fmt=(v:any,d=0)=>v==null?'—':Number(v).toLocaleString('ko-KR',{maximumFractionDigits:d});
const bytes=(v:number)=>v==null?'—':v>=1073741824?`${fmt(v/1073741824,1)} GB`:v>=1048576?`${fmt(v/1048576,1)} MB`:`${fmt(v/1024,1)} KB`;
const pct=(v:number)=>v==null?'—':`${fmt(v*100,1)}%`;
const time=(v:number)=>v?new Date(v*1000).toLocaleString('ko-KR'):'—';
const url=(path:string,download=false)=>`/api/file?path=${encodeURIComponent(path)}${download?'&download=true':''}`;
async function api(path:string){const r=await fetch('/api'+path);if(!r.ok)throw Error(`${r.status} · ${await r.text()}`);return r.json();}
function useData(path:string|null,tick=0){const [data,setData]=useState<any>(null);const [error,setError]=useState('');useEffect(()=>{let alive=true;setData(null);setError('');if(path)api(path).then(x=>{if(alive){setData(x);setError('')}}).catch(e=>alive&&setError(e.message));return()=>{alive=false}},[path]);useEffect(()=>{let alive=true;if(path&&tick)api(path).then(x=>{if(alive){setData(x);setError('')}}).catch(e=>alive&&setError(e.message));return()=>{alive=false}},[tick,path]);return {data,error};}
const palette=['#66ddcb','#6da7ff','#d4a2ff','#ffb866','#f07891'];
function Chart({series,xName='업데이트',yName='',height=290,onPoint}:{series:Data[],xName?:string,yName?:string,height?:number,onPoint?:(x:number)=>void}){
 const ref=useRef<HTMLDivElement>(null);useEffect(()=>{if(!ref.current)return;const chart=echarts.init(ref.current,undefined,{renderer:'canvas'});chart.setOption({animation:false,color:palette,backgroundColor:'transparent',textStyle:{color:'#9caebf',fontFamily:'sans-serif'},tooltip:{trigger:'axis',confine:true},legend:{top:0,type:'scroll',textStyle:{color:'#c8d4df'}},grid:{top:52,right:28,bottom:62,left:65},xAxis:{type:xName==='시각'?'time':'value',name:xName,nameLocation:'middle',nameGap:30,splitLine:{show:false},axisLine:{lineStyle:{color:'#354253'}}},yAxis:{type:'value',name:yName,splitLine:{lineStyle:{color:'#243040'}}},dataZoom:[{type:'inside'},{type:'slider',height:16,bottom:0,borderColor:'#334153',textStyle:{color:'#9caebf'}}],series:series.map(s=>({type:'line',showSymbol:false,connectNulls:false,lineStyle:{width:2},...s}))});if(onPoint)chart.on('click',(p:any)=>onPoint(p.value[0]));const ro=new ResizeObserver(()=>chart.resize());ro.observe(ref.current);return()=>{ro.disconnect();chart.dispose()}},[series,xName,yName,height]);return <div ref={ref} style={{height}} role="img" aria-label={`${yName} 그래프`}/>;
}
function Badge({status}:{status:string}){return <span className={'badge '+status?.toLowerCase()}>{({SUCCEEDED:'완료',RUNNING:'실행 중',FAILED:'실패',LOST:'연결 유실',CANCELED:'취소'} as Data)[status]||status}</span>}
function Empty({children}:{children:React.ReactNode}){return <div className="empty">{children}</div>}
function ErrorBox({error}:{error:string}){return error?<div role="alert" className="error">{error}</div>:null}
function Stat({label,value,sub}:{label:string,value:any,sub?:string}){return <div className="stat"><span>{label}</span><strong>{value}</strong>{sub&&<small>{sub}</small>}</div>}
function RunTable({runs,open}:{runs:Data[],open:(id:string)=>void}){return <div className="table-wrap"><table><thead><tr><th>실행</th><th>상태</th><th>Seed</th><th>업데이트</th><th>평가 완주</th><th>시작 시각</th></tr></thead><tbody>{runs.map(r=><tr key={r.id}><td><button className="text-link run-name" onClick={()=>open(r.id)}>{r.id}</button><small>{r.kind==='train'?'PPO 학습':r.kind==='evaluate'?'평가':r.kind} · {r.task}</small></td><td><Badge status={r.status}/></td><td>{r.seed??'—'}</td><td>{fmt(r.latest?.iteration)}</td><td>{r.evaluation?`${r.evaluation.successes}/${r.evaluation.episodes}`:'—'}</td><td className="muted">{time(r.started_at)}</td></tr>)}</tbody></table>{!runs.length&&<Empty>조건에 맞는 실행이 없습니다.</Empty>}</div>}
function Overview({overview,runs,tick,open}:{overview:Data,runs:Data[],tick:number,open:(s:string)=>void}){
 const {data:history}=useData('/telemetry?hours=1',tick);const sys=overview.system;const c=overview.counts||{};
 return <><div className="stats"><Stat label="실행 중" value={fmt(c.running)} sub={`총 ${fmt(c.runs)}개 실행 기록`}/><Stat label="학습 / 평가" value={`${fmt(c.train)} / ${fmt(c.evaluate)}`} sub="각 attempt를 별도 기록"/><Stat label="평가 영상 묶음" value={fmt(c.videos)} sub="실제 학습 영상 별도 표시"/><Stat label="디스크 여유" value={bytes(sys?.disk_free_bytes)} sub={`RAM ${bytes(sys?.ram_used_bytes)} / ${bytes(sys?.ram_total_bytes)}`}/></div>
 <div className="section-head"><h2>GPU 자원</h2><span className="muted">CPU {fmt(sys?.cpu_percent,1)}% · {time(sys?.sampled_at)}</span></div>
 {sys?.gpu_error&&<ErrorBox error={sys.gpu_error}/>}
 <div className="gpu-grid">{sys?.gpus?.map((g:Data)=><section className="gpu" key={g.uuid}><div className="row"><span className="chip"><Cpu size={16}/> GPU {g.index}</span><span className={g.processes?.length?'live':'muted'}>{g.processes?.length?'사용 중':'유휴'}</span></div><h3>{g.name.replace('NVIDIA GeForce ','')}</h3><div className="gpu-percent">{fmt(g.utilization)}<small>%</small></div><div className="meter"><i style={{width:`${g.utilization||0}%`}}/></div><div className="gpu-details"><span>VRAM <b>{fmt(g.memory_used_mb/1024,1)} / {fmt(g.memory_total_mb/1024)} GB</b></span><span>온도 / 전력 <b>{fmt(g.temperature_c)}°C / {fmt(g.power_w)} W</b></span><span>SM clock <b>{fmt(g.clock_mhz)} MHz</b></span></div><small className="uuid" title={g.uuid}>{g.uuid}</small>{g.runs?.map((id:string)=><button className="text-link" key={id} onClick={()=>open(id)}>{id}</button>)}{g.processes?.map((p:Data)=><small key={p.pid}>PID {p.pid} · {fmt(p.memory_mb)} MB</small>)}</section>)}</div>
 <section className="panel"><div className="section-head"><h2>GPU 사용률 · 최근 1시간</h2><span className="muted">모니터링 시작 이후 수집</span></div>{history?.length?<Chart xName="시각" yName="%" series={(sys?.gpus||[]).map((g:Data)=>({name:`GPU ${g.index}`,data:history.map((s:Data)=>[s.sampled_at*1000,s.gpus.find((x:Data)=>x.uuid===g.uuid)?.utilization??null])}))}/>:<Empty>자원 기록을 수집하고 있습니다.</Empty>}</section>
 <section className="panel"><div className="section-head"><h2>최근 실행</h2><span className="muted">실패·중단 기록 포함</span></div><RunTable runs={runs.slice(0,8)} open={open}/></section></>;
}
function Runs({runs,open}:{runs:Data[],open:(id:string)=>void}){const [q,setQ]=useState('');const [kind,setKind]=useState('all');const [status,setStatus]=useState('all');return <section className="panel"><div className="toolbar"><label className="search"><Search size={17}/><input placeholder="실행 이름·과제 검색" value={q} onChange={e=>setQ(e.target.value)}/></label><select aria-label="작업 종류" value={kind} onChange={e=>setKind(e.target.value)}><option value="all">모든 작업</option><option value="train">학습</option><option value="evaluate">평가</option></select><select aria-label="실행 상태" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">모든 상태</option>{['SUCCEEDED','RUNNING','FAILED','LOST'].map(s=><option key={s}>{s}</option>)}</select></div><RunTable runs={runs.filter(r=>(r.id+' '+r.task).includes(q)&&(kind==='all'||r.kind===kind)&&(status==='all'||r.status===status))} open={open}/></section>}
function MetricCharts({rows}:{rows:Data[]}){return <div className="two-col"><section className="panel"><h2>학습 중 완료 접촉 수</h2><Chart yName="접촉 / episode" series={[{name:'평균 완료 접촉',data:rows.map(r=>[r.iteration,r.mean_completed_contacts??null])}]}/></section><section className="panel"><h2>학습 중 episode 성공 비율</h2><Chart yName="%" series={[{name:'해당 update의 종료 episode',data:rows.map(r=>[r.iteration,r.episodes?100*r.successes/r.episodes:null])}]}/><small>고정 개발군의 평가 성공률과 다릅니다.</small></section><section className="panel"><h2>PPO loss</h2><Chart series={['value_function','surrogate','entropy'].map(k=>({name:k,data:rows.map(r=>[r.iteration,r.losses?.[k]??null])}))}/></section><section className="panel"><h2>업데이트 소요 시간</h2><Chart yName="초" series={[{name:'wall seconds / update',data:rows.map(r=>[r.iteration,r.wall_seconds])}]}/></section></div>}
function useMetrics(id:string|null,tick:number){const [rows,setRows]=useState<Data[]>([]);const [error,setError]=useState('');const cursor=useRef(-1);const busy=useRef(false);const generation=useRef(0);useEffect(()=>{generation.current++;cursor.current=-1;busy.current=false;setRows([]);setError('')},[id]);useEffect(()=>{if(!id||busy.current)return;busy.current=true;let alive=true;const gen=generation.current;async function load(){let next=cursor.current;let buffer:Data[]=[];try{while(true){const d=await api(`/runs/${encodeURIComponent(id!)}/metrics?after=${next}`);buffer.push(...d.rows);next=d.next_cursor;if(!d.has_more)break;}if(alive&&generation.current===gen){cursor.current=next;setRows(r=>[...r,...buffer]);setError('')}}catch(e:any){if(alive)setError(e.message)}finally{if(gen===generation.current)busy.current=false}}load();return()=>{alive=false}},[id,tick]);return {rows,error}}
function RunDetail({id,tick,back,openVideo}:{id:string,tick:number,back:()=>void,openVideo:(v:Data)=>void}){
 const {data:r,error}=useData(`/runs/${encodeURIComponent(id)}`,tick);const {rows,error:metricError}=useMetrics(id,tick);const {data:logs}=useData(`/runs/${encodeURIComponent(id)}/log`,tick);const {data:ev}=useData(r?.kind==='evaluate'?`/runs/${encodeURIComponent(id)}/evaluation`:null);const [tab,setTab]=useState('metrics');
 if(!r)return <><ErrorBox error={error}/><Empty>실행 정보를 불러오는 중…</Empty></>;
 return <><button className="back" onClick={back}><ArrowLeft size={16}/> 실행 목록</button><div className="detail-title"><h2>{id}</h2><Badge status={r.status}/></div><p className="muted">{r.task} · seed {r.seed??'—'} · {fmt(r.num_envs)} 환경 · {time(r.started_at)}</p><div className="stats"><Stat label="업데이트" value={fmt(r.latest?.iteration)} sub={`환경 step ${fmt(r.latest?.total_environment_steps)}`}/><Stat label="고정 평가 완주율" value={pct(r.evaluation?.success_rate)} sub={r.evaluation?`${r.evaluation.successes} / ${r.evaluation.episodes} episodes`:'이 실행에 평가 결과 없음'}/><Stat label="평가 평균 접촉" value={fmt(r.evaluation?.mean_completed_contacts,2)} sub="완주 조건 4회 · 순차 과제"/><Stat label="GPU 자원 회수" value={r.supervisor?.resource_released?'확인':r.supervisor?'미확인':'기록 없음'} sub={r.supervisor?.gpu_uuid}/></div>
 <div className="tabs">{[['metrics','지표·평가'],['config','설정·계보'],['log','로그'],['files','파일·영상']].map(([key,label])=><button className={tab===key?'active':''} key={key} onClick={()=>setTab(key)}>{label}</button>)}</div><ErrorBox error={error||metricError}/>
 {tab==='metrics'&&<>{rows.length?<MetricCharts rows={rows}/>:!ev&&<Empty>이 실행에는 학습 지표가 없습니다.</Empty>}{ev&&<section className="panel"><h2>고정 개발군 episode</h2><p className="muted">완주율 95% Wilson 구간: {ev.success_wilson95?.map((x:number)=>pct(x)).join(' – ')}</p><div className="table-wrap"><table><thead><tr><th>시나리오</th><th>결과</th><th>완료 접촉</th><th>최종 오차</th><th>제어 steps</th></tr></thead><tbody>{ev.results.map((e:Data)=><tr key={e.scenario_id}><td>{e.scenario_id}</td><td>{e.success?'성공':e.failure?'실패':'시간초과'}</td><td>{e.completed_contacts??'—'}</td><td>{fmt(e.final_error_m*100,2)} cm</td><td>{e.length}</td></tr>)}</tbody></table></div></section>}</>}
 {tab==='config'&&<section className="panel"><h2>원본 설정·checkpoint 계보</h2><pre>{JSON.stringify(r.run,null,2)}</pre></section>}{tab==='log'&&<section className="panel"><h2>로그 · 마지막 64 KB</h2><pre className="log">{logs?.text||'로그를 불러오는 중…'}</pre></section>}{tab==='files'&&<section className="panel"><h2>연결된 영상</h2>{r.related_videos.length?r.related_videos.map((v:Data)=><button className="video-link" key={v.id} onClick={()=>openVideo(v)}><Film size={20}/>{v.title}<ChevronRight size={18}/></button>):<Empty>완료된 평가 영상이 없습니다.</Empty>}<h2>실행 파일</h2>{r.files.map((f:Data)=><a className="file-row" key={f.path} href={url(f.path,true)}><span>{f.name}</span><small>{bytes(f.size)}</small><Download size={16}/></a>)}</section>}</>;
}
function Compare({runs,tick}:{runs:Data[],tick:number}){
 const training=runs.filter(r=>r.kind==='train');const [selected,setSelected]=useState<string[]>(()=>training.filter(r=>/^t0s-v2-seed[0-3]$/.test(r.id)).map(r=>r.id));const [key,setKey]=useState('mean_completed_contacts');const [data,setData]=useState<Data>({});const [error,setError]=useState('');
 useEffect(()=>{let alive=true;Promise.all(selected.map(async id=>{let rows:Data[]=[];let cursor=-1;while(true){const d=await api(`/runs/${encodeURIComponent(id)}/metrics?after=${cursor}`);rows.push(...d.rows);cursor=d.next_cursor;if(!d.has_more)break;}return [id,rows] as const})).then(pairs=>{if(alive){setData(Object.fromEntries(pairs));setError('')}}).catch(e=>alive&&setError(e.message));return()=>{alive=false}},[selected.join('|'),tick]);
 return <><section className="panel"><div className="section-head"><h2>학습 실행 비교</h2><select value={key} aria-label="비교 지표" onChange={e=>setKey(e.target.value)}><option value="mean_completed_contacts">평균 완료 접촉 수</option><option value="success_rate">학습 episode 성공 비율</option><option value="mean_final_error_m">최종 발 위치 오차 (m)</option><option value="wall_seconds">업데이트 소요 시간 (s)</option></select></div><div className="compare-picker">{training.map(r=><label key={r.id}><input type="checkbox" checked={selected.includes(r.id)} disabled={!selected.includes(r.id)&&selected.length>=4} onChange={()=>setSelected(s=>s.includes(r.id)?s.filter(x=>x!==r.id):[...s,r.id])}/>{r.id}</label>)}</div><small>최대 4개. 같은 과제·계산 예산인지 설정을 함께 확인하세요.</small><ErrorBox error={error}/>{selected.length?<Chart height={390} series={selected.map(id=>({name:id,data:(data[id]||[]).map((r:Data)=>[r.iteration,key==='success_rate'?(r.episodes?r.successes/r.episodes:null):r[key]??null])}))}/>:<Empty>비교할 실행을 선택하세요.</Empty>}</section><section className="panel"><h2>연결된 고정 평가</h2><div className="table-wrap"><table><thead><tr><th>학습 실행</th><th>평가 실행</th><th>완주</th><th>평균 접촉</th></tr></thead><tbody>{selected.flatMap(id=>runs.filter(r=>r.id===id+'__final-evaluation').map(r=><tr key={r.id}><td>{id}</td><td>{r.id}</td><td>{r.evaluation?.successes}/{r.evaluation?.episodes}</td><td>{fmt(r.evaluation?.mean_completed_contacts,2)}</td></tr>))}</tbody></table></div><small>학습 중 지표와 별도로 집계한 평가 결과입니다.</small></section></>;
}
function VideoPlayer({v,back,openRun}:{v:Data,back:()=>void,openRun:(id:string)=>void}){
 const [mode,setMode]=useState('evaluation');const [env,setEnv]=useState(0);const [position,setPosition]=useState(0);const video=useRef<HTMLVideoElement>(null);
 const training=v.training_video;const trainingName=typeof training==='string'?training:training?.video||training?.path||training?.file;
 const videoPath=mode==='training'?`${v.path}/${trainingName}`:v.video_path;
 const replayPath=`${v.path}/${mode==='training'?'training-replay.json':'replay.json'}`;
 const {data:replay,error}=useData(`/replay?path=${encodeURIComponent(replayPath)}&env=${env}`);
 const samples:Data[]=replay?.samples||[];const selected=samples.length?samples.reduce((a,b)=>Math.abs(b.time-position)<Math.abs(a.time-position)?b:a):null;
 function seek(t:number){if(video.current){video.current.currentTime=t;setPosition(t)}}
 return <><button className="back" onClick={back}><ArrowLeft size={16}/> 영상 목록</button><h2 className="video-title">{v.title}</h2><div className="toolbar"><button className={mode==='evaluation'?'selected':''} onClick={()=>{setMode('evaluation');setPosition(0)}}>최종 평가</button>{trainingName&&<button className={mode==='training'?'selected':''} onClick={()=>{setMode('training');setPosition(0)}}>실제 병렬 학습</button>}<button onClick={()=>openRun(v.evaluation_run)}>평가 실행 <ExternalLink size={14}/></button><a className="button" href={url(videoPath,true)}><Download size={16}/> MP4 다운로드</a></div><div className="replay-layout"><div><video key={videoPath} ref={video} className="player" controls preload="metadata" poster={mode==='evaluation'?url(v.preview_path):undefined} src={url(videoPath)} onTimeUpdate={e=>setPosition(e.currentTarget.currentTime)}/><p className="muted">{mode==='training'?'실제 PPO 업데이트 중 촬영':'고정 정책 평가'} · {v.video_layout==='parallel'?'병렬 16개':'단일 로봇'} · simulator 시간 {fmt(position,2)} s</p><p className="muted">완료 후 자동 리셋이 보일 수 있습니다. 평가 통계는 각 환경의 첫 episode만 포함합니다.</p></div><section className="panel replay-info"><h3>전체 평가</h3><strong className="big">{v.aggregate.successes}<span> / {v.aggregate.episodes}</span></strong><p>평균 완료 접촉 {fmt(v.aggregate.mean_completed_contacts,2)} / 4</p><hr/><label>관측할 로봇<select value={env} onChange={e=>setEnv(Number(e.target.value))}>{(replay?.metadata?.visible_env_ids||[0]).map((id:number,i:number)=><option key={id} value={i}>환경 {id}</option>)}</select></label><dl><dt>접촉 진행 단계</dt><dd>{selected?.stage==null?'미수집':`${selected.stage} / 4`}</dd><dt>현재 단계</dt><dd>{selected?.phase==null?'미수집':selected.phase===0?'발 들기':'착지'}</dd><dt>몸체 높이</dt><dd>{fmt(selected?.root_z,3)} m</dd><dt>학습 업데이트</dt><dd>{selected?.learning_iteration??'평가 중'}</dd></dl><small>접촉력·충격·행동 채널은 이 병렬 기록에 없습니다.</small></section></div><ErrorBox error={error}/>{samples.length>0&&<section className="panel"><div className="section-head"><h2>영상과 센서 위치 기록</h2><span>{fmt(position,2)} s</span></div><input className="scrubber" aria-label="영상 시간" type="range" min="0" max={samples.at(-1)?.time||1} step="0.04" value={position} onChange={e=>seek(Number(e.target.value))}/><Chart xName="simulator 시간 (s)" yName="월드 높이 (m)" onPoint={seek} series={[{name:'몸체',data:samples.map(s=>[s.time,s.root_z])},...['발 0','발 1','발 2','발 3'].map((name,i)=>({name,data:samples.map(s=>[s.time,s.feet_z?.[i]??null])}))]}/></section>}</>;
}
function Videos({videos,open}:{videos:Data[],open:(v:Data)=>void}){const [q,setQ]=useState('');return <><div className="toolbar"><label className="search"><Search size={17}/><input placeholder="과제·seed·업데이트 검색" value={q} onChange={e=>setQ(e.target.value)}/></label><span className="muted">평가와 실제 학습 장면을 구분합니다.</span></div><div className="video-grid">{videos.filter(v=>v.title.toLowerCase().includes(q.toLowerCase())).map(v=><button className="video-card" key={v.id} onClick={()=>open(v)}><div className="thumbnail"><img loading="lazy" src={url(v.preview_path)} alt={`${v.evaluation_run} 평가 장면`}/><span><Film size={14}/>{v.video_layout==='parallel'?'16대 병렬':'단일 로봇'}</span></div><div className="video-body"><small>{v.task.includes('sequential')?'T0S · 순차 발 디딤':'T0 · 정적 목표 접촉'} · seed {v.seed??'—'}</small><h3>{v.updates} updates · {v.aggregate.successes}/{v.aggregate.episodes} 완주</h3><p>{v.title}</p>{v.training_video&&<span className="training-tag">실제 학습 영상 포함</span>}</div></button>)}</div></>}
function Files({tick}:{tick:number}){const [path,setPath]=useState('result');const [selected,setSelected]=useState<Data|null>(null);const {data,error}=useData('/files?path='+encodeURIComponent(path),tick);const {data:preview,error:previewError}=useData(selected&&!/\.(mp4|png|jpe?g)$/.test(selected.name)?'/preview?path='+encodeURIComponent(selected.path):null);return <><div className="toolbar">{['result','artifacts','docs','configs'].map(root=><button className={path.split('/')[0]===root?'selected':''} key={root} onClick={()=>{setPath(root);setSelected(null)}}>{root}</button>)}</div><div className="breadcrumbs">{path.split('/').map((part,i)=><React.Fragment key={i}><button onClick={()=>setPath(path.split('/').slice(0,i+1).join('/'))}>{part}</button><ChevronRight size={14}/></React.Fragment>)}</div><ErrorBox error={error}/><section className="panel"><div className="table-wrap"><table><thead><tr><th>이름</th><th>크기</th><th>변경 시각</th><th>다운로드</th></tr></thead><tbody>{data?.entries.map((f:Data)=><tr key={f.path}><td><button className="text-link file-name" onClick={()=>f.directory?(setPath(f.path),setSelected(null)):setSelected(f)}>{f.directory&&<FolderOpen size={17}/>} {f.name}</button></td><td>{f.directory?'—':bytes(f.size)}</td><td>{time(f.modified_at)}</td><td>{!f.directory&&<a href={url(f.path,true)} aria-label={`${f.name} 다운로드`}><Download size={17}/></a>}</td></tr>)}</tbody></table></div></section>{selected&&<section className="panel"><div className="section-head"><h2>{selected.name}</h2><a href={url(selected.path,true)}>원본 다운로드</a></div>{selected.name.endsWith('.mp4')?<video className="player" src={url(selected.path)} controls/>:/\.(png|jpe?g)$/.test(selected.name)?<img className="file-image" src={url(selected.path)} alt={selected.name}/>:<><ErrorBox error={previewError}/>{preview?.truncated&&<p>미리보기는 처음 256 KB입니다. 전체 내용은 원본을 다운로드하세요.</p>}<pre>{preview?.text||'미리보기 로딩 중…'}</pre></>}</section>}</>}
const tabs=[['overview','전체 현황',LayoutDashboard],['runs','실행 기록',FlaskConical],['compare','실험 비교',GitCompareArrows],['videos','영상 라이브러리',Film],['files','파일 탐색',FolderOpen]] as const;
function App(){const [page,setPage]=useState('overview');const [runId,setRunId]=useState<string|null>(null);const [video,setVideo]=useState<Data|null>(null);const [tick,setTick]=useState(0);const [connected,setConnected]=useState(false);const {data:overview,error}=useData('/overview',tick);const {data:runs=[],error:runError}=useData('/runs',tick);const {data:videos=[]}=useData('/videos',tick);
 useEffect(()=>{const source=new EventSource('/api/events');source.addEventListener('refresh',()=>{setConnected(true);setTick(t=>t+1)});source.addEventListener('unavailable',()=>setConnected(false));source.onerror=()=>setConnected(false);const fallback=setInterval(()=>setTick(t=>t+1),10000);return()=>{source.close();clearInterval(fallback)}},[]);
 const openRun=(id:string)=>{setRunId(id);setVideo(null);setPage('runs')};const openVideo=(v:Data)=>{setVideo(v);setRunId(null);setPage('videos')};
 const health=overview?.collector;const stale=!health||Date.now()/1000-health.last_scan>15;
 return <div className="app"><aside className="sidebar"><a className="brand" href="/" aria-label="parkour 홈"><Activity size={27}/><span>parkour<small>RESEARCH MONITOR</small></span></a><div className="nav-label">WORKSPACE</div><nav>{tabs.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);setRunId(null);setVideo(null)}}><Icon size={19}/>{label}{id==='videos'&&<span className="nav-count">{videos?.length||0}</span>}</button>)}</nav><div className="sidebar-bottom"><span className="chip">A1 · SIMULATION</span><p>사전 지도 기반 파쿠르 연구</p><small>RTX 4090 × 4<br/>수집기 → 실험 기록 → 평가</small></div></aside><main><header><div><span className="eyebrow">PARKOUR LAB / MONITOR</span><h1>{tabs.find(t=>t[0]===page)?.[1]}</h1></div><div className="connection"><span className={connected&&!stale?'live':'warning'}><i/>{stale?'수집 지연':connected?'실시간 연결':'재연결 중'}</span><button aria-label="새로고침" onClick={()=>setTick(t=>t+1)}><RefreshCw size={17}/></button></div></header><ErrorBox error={error||runError}/>{health?.errors?.length>0&&<details className="error"><summary>수집 경고 {health.errors.length}건</summary><pre>{JSON.stringify(health.errors,null,2)}</pre></details>}{stale&&<div className="notice">수집기의 최신 상태를 확인 중입니다. 마지막 수집: {time(health?.last_scan)}</div>}{!overview?<Empty>연구 기록을 불러오는 중…</Empty>:page==='overview'?<Overview overview={overview} runs={runs||[]} tick={tick} open={openRun}/>:page==='runs'?runId?<RunDetail key={runId} id={runId} tick={tick} back={()=>setRunId(null)} openVideo={openVideo}/>:<Runs runs={runs||[]} open={openRun}/>:page==='compare'?<Compare runs={runs||[]} tick={Math.floor(tick/5)}/>:page==='videos'?video?<VideoPlayer key={video.id} v={video} back={()=>setVideo(null)} openRun={openRun}/>:<Videos videos={videos||[]} open={openVideo}/>:<Files tick={tick}/>}<footer>parkour · 연구 원본은 artifacts/와 result/에 보존 · 마지막 수집 {time(health?.last_scan)}</footer></main></div>
}

createRoot(document.getElementById('root')!).render(<App/>);
